spring.application.name=weather
server.port=8080

openweathermap.api-key=2ff074106b2eb86f337ccee6feb6cd33
openweathermap.base-url=https://api.openweathermap.org/data/2.5

logging.level.org.springframework.web.reactive=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.reactor.netty.http.client=DEBUG
logging.level.org.springframework.web.servlet=DEBUG
logging.level.org.springframework.cache=DEBUG
